version: '3.8'
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: rechain
      MINIO_SECRET_KEY: rechain123
    command: server /data

  etcd:
    image: quay.io/coreos/etcd:v3.5.7
    ports:
      - "2379:2379"
      - "2380:2380"
    command: etcd --advertise-client-urls http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379

  gcl-mock:
    build:
      context: ..
      dockerfile: Dockerfile.gcl
    ports:
      - "8081:8081"
    environment:
      PORT: 8081
