all:
  children:
    decube_servers:
      hosts:
        decube-node-1:
          ansible_host: 10.0.1.10
          ansible_user: ubuntu
          cluster_id: cluster-001
        decube-node-2:
          ansible_host: 10.0.1.11
          ansible_user: ubuntu
          cluster_id: cluster-001
        decube-node-3:
          ansible_host: 10.0.1.12
          ansible_user: ubuntu
          cluster_id: cluster-001
      vars:
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_python_interpreter: /usr/bin/python3

